feat: [DP-440/DP-816] - crud for user, role dto
quckoo-org/api-tips-backend pull request #7
Opened 2024-12-05 08:04 UTC by kirillgileadd

## Чеклист

- [ ] crud для юзера
- [ ] сущность роли
- [ ] rpc ecx builder

---

2024-12-12 10:07 UTC, dolgosheev commented on .helm/values.yaml.gotmpl
> +singress:
?

2024-12-12 10:08 UTC, dolgosheev commented on proto/user/v1/user.proto
> +
Статуса нет

2024-12-12 10:08 UTC, dolgosheev commented on proto/user/v1/user.proto
> +  optional int32 countryId = 5;
cca3

2024-12-12 10:08 UTC, dolgosheev commented on proto/user/v1/user.proto
> +  optional int32 countryId = 5;
не соответствует google code style country_id

2024-12-12 10:08 UTC, dolgosheev commented on proto/user/v1/user.proto
> +  //   google.protobuf.StringValue email = 2;
yagni

2024-12-12 10:08 UTC, dolgosheev commented on proto/user/v1/user.proto
> +}
нет статуса

2024-12-12 10:09 UTC, dolgosheev commented on proto/user/v1/user.proto
> +  int32 pageSize = 2;
int64

2024-12-12 10:09 UTC, dolgosheev requested changes
Требуются доработки

2024-12-25 12:34 UTC, JustFeitan approved these changes

2024-12-25 12:35 UTC, merged